
name: proninteam

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: .env
    volumes:
      - static:/static/
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - "8777:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
    depends_on:
      - backend
  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - backend
  rabbitmq:
    image: rabbitmq
    env_file: .env
    ports:
      - 5672:5672
    depends_on:
      - backend
