# Generated by Django 5.0.6 on 2024-05-17 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=156, verbose_name="Название")),
            ],
            options={
                "verbose_name": "цель сбора",
                "verbose_name_plural": "Цели сбора",
                "default_related_name": "reason",
            },
        ),
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=156, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "target",
                    models.PositiveIntegerField(
                        default=None, null=True, verbose_name="Необходимая сумма"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None, null=True, upload_to="collect/images"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("collection_end_time", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор сбора",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.reason",
                        verbose_name="Цель сбора",
                    ),
                ),
            ],
            options={
                "verbose_name": "групповой сбор",
                "verbose_name_plural": "Групповые сборы",
                "default_related_name": "collect",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="сумма")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payments.collect",
                        verbose_name="Групповой сбор",
                    ),
                ),
                (
                    "donator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Донатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "платеж",
                "verbose_name_plural": "Платежи",
                "default_related_name": "payments",
            },
        ),
    ]
